<?php

namespace kriss\envGeneratorExample\simple;

class Generator extends \kriss\envGenerator\Generator
{
    protected function generateFiles($config, $env, $envObj)
    {
        $commonHeader = '# this file is generated by ' . __CLASS__;
        $content = $this->getEnvProject($config);
        $this->fileGenerate($env, '.env', implode("\n", [$commonHeader, $content]));
    }

    protected function getEnvProject($config)
    {
        return <<<EOL
ENV={$config['env']}
        
APP_KEY={$config['appKey']},
APP_SECRET={$config['appSecret']},
EOL;
    }
}